/**
 * @fileoverview gRPC-Web generated client stub for study
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: study.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as study_pb from './study_pb'; // proto import: "study.proto"


export class StudyServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorJoinSession = new grpcWeb.MethodDescriptor(
    '/study.StudyService/JoinSession',
    grpcWeb.MethodType.UNARY,
    study_pb.User,
    study_pb.SessionToken,
    (request: study_pb.User) => {
      return request.serializeBinary();
    },
    study_pb.SessionToken.deserializeBinary
  );

  joinSession(
    request: study_pb.User,
    metadata?: grpcWeb.Metadata | null): Promise<study_pb.SessionToken>;

  joinSession(
    request: study_pb.User,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: study_pb.SessionToken) => void): grpcWeb.ClientReadableStream<study_pb.SessionToken>;

  joinSession(
    request: study_pb.User,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: study_pb.SessionToken) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/study.StudyService/JoinSession',
        request,
        metadata || {},
        this.methodDescriptorJoinSession,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/study.StudyService/JoinSession',
    request,
    metadata || {},
    this.methodDescriptorJoinSession);
  }

  methodDescriptorStreamSessionUpdates = new grpcWeb.MethodDescriptor(
    '/study.StudyService/StreamSessionUpdates',
    grpcWeb.MethodType.SERVER_STREAMING,
    study_pb.SessionToken,
    study_pb.SessionEvent,
    (request: study_pb.SessionToken) => {
      return request.serializeBinary();
    },
    study_pb.SessionEvent.deserializeBinary
  );

  streamSessionUpdates(
    request: study_pb.SessionToken,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<study_pb.SessionEvent> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/study.StudyService/StreamSessionUpdates',
      request,
      metadata || {},
      this.methodDescriptorStreamSessionUpdates);
  }

  methodDescriptorSendAction = new grpcWeb.MethodDescriptor(
    '/study.StudyService/SendAction',
    grpcWeb.MethodType.UNARY,
    study_pb.SessionAction,
    study_pb.Empty,
    (request: study_pb.SessionAction) => {
      return request.serializeBinary();
    },
    study_pb.Empty.deserializeBinary
  );

  sendAction(
    request: study_pb.SessionAction,
    metadata?: grpcWeb.Metadata | null): Promise<study_pb.Empty>;

  sendAction(
    request: study_pb.SessionAction,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: study_pb.Empty) => void): grpcWeb.ClientReadableStream<study_pb.Empty>;

  sendAction(
    request: study_pb.SessionAction,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: study_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/study.StudyService/SendAction',
        request,
        metadata || {},
        this.methodDescriptorSendAction,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/study.StudyService/SendAction',
    request,
    metadata || {},
    this.methodDescriptorSendAction);
  }

  methodDescriptorSaveNote = new grpcWeb.MethodDescriptor(
    '/study.StudyService/SaveNote',
    grpcWeb.MethodType.UNARY,
    study_pb.NoteRequest,
    study_pb.Empty,
    (request: study_pb.NoteRequest) => {
      return request.serializeBinary();
    },
    study_pb.Empty.deserializeBinary
  );

  saveNote(
    request: study_pb.NoteRequest,
    metadata?: grpcWeb.Metadata | null): Promise<study_pb.Empty>;

  saveNote(
    request: study_pb.NoteRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: study_pb.Empty) => void): grpcWeb.ClientReadableStream<study_pb.Empty>;

  saveNote(
    request: study_pb.NoteRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: study_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/study.StudyService/SaveNote',
        request,
        metadata || {},
        this.methodDescriptorSaveNote,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/study.StudyService/SaveNote',
    request,
    metadata || {},
    this.methodDescriptorSaveNote);
  }

  methodDescriptorGetMyNotes = new grpcWeb.MethodDescriptor(
    '/study.StudyService/GetMyNotes',
    grpcWeb.MethodType.UNARY,
    study_pb.SessionToken,
    study_pb.NoteResponse,
    (request: study_pb.SessionToken) => {
      return request.serializeBinary();
    },
    study_pb.NoteResponse.deserializeBinary
  );

  getMyNotes(
    request: study_pb.SessionToken,
    metadata?: grpcWeb.Metadata | null): Promise<study_pb.NoteResponse>;

  getMyNotes(
    request: study_pb.SessionToken,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: study_pb.NoteResponse) => void): grpcWeb.ClientReadableStream<study_pb.NoteResponse>;

  getMyNotes(
    request: study_pb.SessionToken,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: study_pb.NoteResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/study.StudyService/GetMyNotes',
        request,
        metadata || {},
        this.methodDescriptorGetMyNotes,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/study.StudyService/GetMyNotes',
    request,
    metadata || {},
    this.methodDescriptorGetMyNotes);
  }

}

